# Generated by Django 4.2.5 on 2023-10-12 11:12

from django.db import migrations

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# lnschema_lamin1.migrations.0011_migrate_to_integer_pks
# lnschema_lamin1.migrations.0012_export_legacy_data


class Migration(migrations.Migration):
    replaces = [
        ("lnschema_lamin1", "0001_initial"),
        ("lnschema_lamin1", "0002_alter_biosample_options_alter_experiment_options_and_more"),
        ("lnschema_lamin1", "0003_alter_biosample_created_by_and_more"),
        ("lnschema_lamin1", "0004_remove_treatment_target_genes_treatmenttarget_and_more"),
        ("lnschema_lamin1", "0005_alter_treatmenttarget_created_by_and_more"),
        ("lnschema_lamin1", "0006_remove_treatment_target_treatment_targets"),
        ("lnschema_lamin1", "0007_rename_batch_name_biosample_batch_and_more"),
        ("lnschema_lamin1", "0008_platewell_delete_well"),
        ("lnschema_lamin1", "0009_alter_platewell_id"),
        ("lnschema_lamin1", "0010_rename_platewell_well"),
        ("lnschema_lamin1", "0011_migrate_to_integer_pks"),
        ("lnschema_lamin1", "0012_export_legacy_data"),
    ]

    dependencies = [
        ("lnschema_core", "0001_initial"),
        ("lnschema_core", "0019_dataset_reference_dataset_reference_type_and_more"),
        ("lnschema_core", "0008_file_hash_type_transform_parents"),
        ("lnschema_bionty", "0006_alter_biontysource_options_alter_cellline_options_and_more"),
        ("lnschema_core", "0007_feature_synonyms_featureset_field_and_more"),
        ("lnschema_core", "0023_export_legacy_data"),
        ("lnschema_bionty", "0001_initial"),
    ]

    operations = []  # type: ignore
