# Generated by Django 4.2.1 on 2023-07-03 14:17

import django.db.models.deletion
import lnschema_core.users
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0007_feature_synonyms_featureset_field_and_more"),
        (
            "lnschema_lamin1",
            "0002_alter_biosample_options_alter_experiment_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="biosample",
            name="created_by",
            field=models.ForeignKey(
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_biosamples",
                to="lnschema_core.user",
            ),
        ),
        migrations.AlterField(
            model_name="techsample",
            name="created_by",
            field=models.ForeignKey(
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_techsamples",
                to="lnschema_core.user",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="created_by",
            field=models.ForeignKey(
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_treatments",
                to="lnschema_core.user",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="ontology_id",
            field=models.CharField(db_index=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="pubchem_id",
            field=models.CharField(db_index=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="sequence",
            field=models.TextField(db_index=True, default=None, null=True),
        ),
    ]
