# Generated by Django 4.2.1 on 2023-07-04 12:42

import django.db.models.deletion
import lnschema_core.users
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0007_feature_synonyms_featureset_field_and_more"),
        (
            "lnschema_lamin1",
            "0004_remove_treatment_target_genes_treatmenttarget_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmenttarget",
            name="created_by",
            field=models.ForeignKey(
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_treatment_targets",
                to="lnschema_core.user",
            ),
        ),
        migrations.AlterField(
            model_name="treatmenttarget",
            name="files",
            field=models.ManyToManyField(related_name="treatment_targets", to="lnschema_core.file"),
        ),
    ]
