# Generated by Django 4.2.1 on 2023-07-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_lamin1", "0005_alter_treatmenttarget_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatment",
            name="target",
        ),
        migrations.AddField(
            model_name="treatment",
            name="targets",
            field=models.ManyToManyField(related_name="treatments", to="lnschema_lamin1.treatmenttarget"),
        ),
    ]
