# Generated by Django 4.2.1 on 2023-07-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0008_file_hash_type_transform_parents"),
        ("lnschema_lamin1", "0007_rename_batch_name_biosample_batch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlateWell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate", models.IntegerField()),
                ("row", models.CharField(default=None, max_length=4)),
                ("column", models.IntegerField()),
                (
                    "files",
                    models.ManyToManyField(related_name="wells", to="lnschema_core.file"),
                ),
            ],
            options={
                "unique_together": {("plate", "row", "column")},
            },
        ),
        migrations.DeleteModel(
            name="Well",
        ),
    ]
