# Generated by Django 4.2.1 on 2023-09-18 11:29

import lnschema_core.ids
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_lamin1", "0008_platewell_delete_well"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platewell",
            name="id",
            field=models.CharField(
                default=lnschema_core.ids.base62_8,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
