# Generated by Django 4.2.1 on 2023-10-19 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_lamin1", "0013_import_legacy_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biosample",
            old_name="species",
            new_name="organism",
        ),
    ]
