# Generated by Django 5.1.12 on 2025-09-29 07:51

import lamindb.base.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pertdb", "0043_biologic_is_locked_biosample_is_locked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biologic",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="biosample",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="combinationperturbation",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="compound",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="compoundperturbation",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="environmentalperturbation",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="geneticperturbation",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="perturbationtarget",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="techsample",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="well",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
    ]
