# Generated by Django 4.2.5 on 2023-10-12 11:19

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lnschema_core", "0046_storage_instance_uid"),
        ("lnschema_bionty", "0023_rename_publicsource_encode_uid"),
    ]

    operations = []  # type: ignore
