# Generated by Django 5.0.6 on 2024-05-16 09:02

import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import lnschema_core.ids
import lnschema_core.users
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# wetlab.migrations.0013_

class Migration(migrations.Migration):

    replaces = [('wetlab', '0001_initial_squashed_0012'), ('wetlab', '0013_import_legacy_data'), ('wetlab', '0014_rename_species_biosample_organism'), ('wetlab', '0015_rename_files_biosample_artifacts_and_more'), ('wetlab', '0016_rename_datasets_biosample_collections_and_more'), ('wetlab', '0017_remove_biosample_artifacts'), ('wetlab', '0018_well_created_at_well_created_by_well_updated_at')]

    dependencies = [
        ('lnschema_core', '0046_storage_instance_uid'),
    ]

