# Generated by Django 4.2.5 on 2023-10-11 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wetlab", "0001_initial_squashed_0012"),
    ]

    operations = []  # type: ignore
