# Generated by Django 4.2.5 on 2023-12-12 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wetlab", "0014_rename_species_biosample_organism"),
    ]

    operations = []  # type: ignore
