# Generated by Django 4.2.9 on 2024-02-07 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []  # type: ignore

    operations = [
        migrations.RemoveField(
            model_name="biosample",
            name="artifacts",
        ),
        migrations.RemoveField(
            model_name="biosample",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="biosample",
            name="organism",
        ),
    ]
