# Generated by Django 4.2.9 on 2024-02-07 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wetlab", "0016_rename_datasets_biosample_collections_and_more"),
    ]

    operations = []  # type: ignore
