# Generated by Django 5.0.3 on 2024-07-25 12:46

import django.db.models.deletion
import lnschema_core.users
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0055_artifact_type_artifactparamvalue_and_more"),
        ("wetlab", "0021_remove_treatment_compound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compoundtreatment",
            name="artifacts",
            field=models.ManyToManyField(
                related_name="compound_treatments", to="lnschema_core.artifact"
            ),
        ),
        migrations.AddField(
            model_name="environmentaltreatment",
            name="artifacts",
            field=models.ManyToManyField(
                related_name="environmental_treatments", to="lnschema_core.artifact"
            ),
        ),
        migrations.AlterField(
            model_name="combinationtreatment",
            name="artifacts",
            field=models.ManyToManyField(
                related_name="combination_treatments", to="lnschema_core.artifact"
            ),
        ),
        migrations.AlterField(
            model_name="combinationtreatment",
            name="created_by",
            field=models.ForeignKey(
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_combination_treatments",
                to="lnschema_core.user",
            ),
        ),
        migrations.AlterField(
            model_name="compoundtreatment",
            name="targets",
            field=models.ManyToManyField(
                related_name="compound_targets", to="wetlab.treatmenttarget"
            ),
        ),
        migrations.AlterField(
            model_name="environmentaltreatment",
            name="targets",
            field=models.ManyToManyField(
                related_name="environmental_targets", to="wetlab.treatmenttarget"
            ),
        ),
        migrations.AlterField(
            model_name="genetictreatment",
            name="artifacts",
            field=models.ManyToManyField(
                related_name="genetic_treatments", to="lnschema_core.artifact"
            ),
        ),
        migrations.AlterField(
            model_name="genetictreatment",
            name="targets",
            field=models.ManyToManyField(
                related_name="genetic_targets", to="wetlab.treatmenttarget"
            ),
        ),
    ]
