# Generated by Django 5.0.3 on 2024-07-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wetlab", "0022_compoundtreatment_artifacts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compoundtreatment",
            name="duration_unit",
            field=models.CharField(
                choices=[
                    ("second", "SECOND"),
                    ("minute", "MINUTE"),
                    ("hour", "HOUR"),
                    ("day", "DAY"),
                    ("week", "WEEK"),
                    ("month", "MONTH"),
                    ("year", "YEAR"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="environmentaltreatment",
            name="duration_unit",
            field=models.CharField(
                choices=[
                    ("second", "SECOND"),
                    ("minute", "MINUTE"),
                    ("hour", "HOUR"),
                    ("day", "DAY"),
                    ("week", "WEEK"),
                    ("month", "MONTH"),
                    ("year", "YEAR"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
