# Generated by Django 5.2 on 2024-12-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0069_squashed"),
        ("wetlab", "0025_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biosample",
            name="artifacts",
            field=models.ManyToManyField(
                related_name="biosamples",
                through="wetlab.ArtifactBiosample",
                to="lnschema_core.artifact",
            ),
        ),
        migrations.AlterField(
            model_name="techsample",
            name="artifacts",
            field=models.ManyToManyField(
                related_name="techsamples",
                through="wetlab.ArtifactTechsample",
                to="lnschema_core.artifact",
            ),
        ),
    ]
