# Generated by Django 5.1.3 on 2024-12-04 12:37

import lnschema_core.fields
import lnschema_core.ids
import lnschema_core.models
import lnschema_core.users
from django.db import migrations, models
from django.db.models import CASCADE, PROTECT


class Migration(migrations.Migration):
    dependencies = [
        ("bionty", "0041_squashed"),
        ("lnschema_core", "0069_squashed"),
        ("wetlab", "0026_alter_biosample_artifacts_alter_techsample_artifacts"),
    ]

    operations = [
        # Rename Treatment to Perturbation models
        migrations.RenameModel(
            old_name="TreatmentTarget",
            new_name="PerturbationTarget",
        ),
        migrations.RenameModel(
            old_name="GeneticTreatment",
            new_name="GeneticPerturbation",
        ),
        migrations.RenameModel(
            old_name="CompoundTreatment",
            new_name="CompoundPerturbation",
        ),
        migrations.RenameModel(
            old_name="EnvironmentalTreatment",
            new_name="EnvironmentalPerturbation",
        ),
        migrations.RenameModel(
            old_name="CombinationTreatment",
            new_name="CombinationPerturbation",
        ),
        migrations.RenameModel(
            old_name="ArtifactTreatmentTarget",
            new_name="ArtifactPerturbationTarget",
        ),
        migrations.RenameModel(
            old_name="ArtifactGeneticTreatment",
            new_name="ArtifactGeneticPerturbation",
        ),
        migrations.RenameModel(
            old_name="ArtifactCompoundTreatment",
            new_name="ArtifactCompoundPerturbation",
        ),
        migrations.RenameModel(
            old_name="ArtifactEnvironmentalTreatment",
            new_name="ArtifactEnvironmentalPerturbation",
        ),
        migrations.RenameModel(
            old_name="ArtifactCombinationTreatment",
            new_name="ArtifactCombinationPerturbation",
        ),
        # Rename fields in Artifact link models
        migrations.RenameField(
            model_name="ArtifactPerturbationTarget",
            old_name="treatmenttarget",
            new_name="perturbationtarget",
        ),
        migrations.RenameField(
            model_name="ArtifactGeneticPerturbation",
            old_name="genetictreatment",
            new_name="geneticperturbation",
        ),
        migrations.RenameField(
            model_name="ArtifactCompoundPerturbation",
            old_name="compoundtreatment",
            new_name="compoundperturbation",
        ),
        migrations.RenameField(
            model_name="ArtifactEnvironmentalPerturbation",
            old_name="environmentaltreatment",
            new_name="environmentalperturbation",
        ),
        migrations.RenameField(
            model_name="ArtifactCombinationPerturbation",
            old_name="combinationtreatment",
            new_name="combinationperturbation",
        ),
        # Create new Donor model
        migrations.CreateModel(
            name="ArtifactDonor",
            fields=[
                (
                    "created_at",
                    lnschema_core.fields.DateTimeField(
                        auto_now_add=True, db_index=True
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "label_ref_is_name",
                    lnschema_core.fields.BooleanField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "feature_ref_is_name",
                    lnschema_core.fields.BooleanField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "artifact",
                    lnschema_core.fields.ForeignKey(
                        blank=True,
                        on_delete=CASCADE,
                        related_name="links_donor",
                        to="lnschema_core.artifact",
                    ),
                ),
                (
                    "created_by",
                    lnschema_core.fields.ForeignKey(
                        blank=True,
                        default=lnschema_core.users.current_user_id,
                        on_delete=PROTECT,
                        related_name="+",
                        to="lnschema_core.user",
                    ),
                ),
                (
                    "feature",
                    lnschema_core.fields.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=PROTECT,
                        related_name="links_artifactdonor",
                        to="lnschema_core.feature",
                    ),
                ),
                (
                    "run",
                    lnschema_core.fields.ForeignKey(
                        blank=True,
                        default=lnschema_core.models.current_run,
                        null=True,
                        on_delete=PROTECT,
                        related_name="+",
                        to="lnschema_core.run",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(lnschema_core.models.LinkORM, models.Model),
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "created_at",
                    lnschema_core.fields.DateTimeField(
                        auto_now_add=True, db_index=True
                    ),
                ),
                (
                    "updated_at",
                    lnschema_core.fields.DateTimeField(auto_now=True, db_index=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    lnschema_core.fields.CharField(
                        blank=True,
                        default=lnschema_core.ids.base62_12,
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    lnschema_core.fields.CharField(
                        blank=True, db_index=True, default=None, max_length=255
                    ),
                ),
                (
                    "batch",
                    lnschema_core.fields.CharField(
                        blank=True, db_index=True, default=None, max_length=60
                    ),
                ),
                (
                    "description",
                    lnschema_core.fields.TextField(blank=True, default=None, null=True),
                ),
                (
                    "age",
                    lnschema_core.fields.IntegerField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "bmi",
                    lnschema_core.fields.FloatField(
                        blank=True, default=None, null=True
                    ),
                ),
                (
                    "_previous_runs",
                    models.ManyToManyField(related_name="+", to="lnschema_core.run"),
                ),
                (
                    "artifacts",
                    models.ManyToManyField(
                        related_name="donors",
                        through="wetlab.ArtifactDonor",
                        to="lnschema_core.artifact",
                    ),
                ),
                (
                    "created_by",
                    lnschema_core.fields.ForeignKey(
                        blank=True,
                        default=lnschema_core.users.current_user_id,
                        on_delete=PROTECT,
                        related_name="+",
                        to="lnschema_core.user",
                    ),
                ),
                (
                    "diseases",
                    models.ManyToManyField(related_name="donors", to="bionty.disease"),
                ),
                (
                    "ethnicity",
                    lnschema_core.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=PROTECT,
                        related_name="donors",
                        to="bionty.ethnicity",
                    ),
                ),
                (
                    "organism",
                    lnschema_core.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=PROTECT,
                        related_name="donors",
                        to="bionty.organism",
                    ),
                ),
                (
                    "run",
                    lnschema_core.fields.ForeignKey(
                        blank=True,
                        default=lnschema_core.models.current_run,
                        null=True,
                        on_delete=PROTECT,
                        related_name="+",
                        to="lnschema_core.run",
                    ),
                ),
                (
                    "sex",
                    lnschema_core.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=PROTECT,
                        related_name="donors",
                        to="bionty.phenotype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(lnschema_core.models.CanCurate, models.Model),
        ),
        migrations.AddField(
            model_name="artifactdonor",
            name="donor",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                on_delete=PROTECT,
                related_name="links_artifact",
                to="wetlab.donor",
            ),
        ),
        # Add related_name changes for perturbation targets
        migrations.AlterField(
            model_name="PerturbationTarget",
            name="genes",
            field=models.ManyToManyField(
                "bionty.Gene", related_name="perturbation_targets"
            ),
        ),
        migrations.AlterField(
            model_name="PerturbationTarget",
            name="pathways",
            field=models.ManyToManyField(
                "bionty.Pathway", related_name="perturbation_targets"
            ),
        ),
        migrations.AlterField(
            model_name="PerturbationTarget",
            name="proteins",
            field=models.ManyToManyField(
                "bionty.Protein", related_name="perturbation_targets"
            ),
        ),
        migrations.AlterField(
            model_name="geneticperturbation",
            name="sequence",
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="geneticperturbation",
            name="system",
            field=models.CharField(db_index=True, default=None, max_length=32),
        ),
    ]
