# Generated by Django 5.1.3 on 2024-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wetlab", "0026_alter_biosample_artifacts_alter_techsample_artifacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genetictreatment",
            name="sequence",
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="genetictreatment",
            name="system",
            field=models.CharField(db_index=True, default=None, max_length=32),
        ),
    ]
