# Generated by Django 5.2 on 2025-01-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wetlab", "0029_artifactbiologic_biologic_artifactbiologic_biologic"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifactbiologic",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="artifactbiosample",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="artifactcombinationperturbation",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="artifactcompound",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="artifactcompoundperturbation",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="artifactdonor",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="artifactenvironmentalperturbation",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="artifactexperiment",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="artifactgeneticperturbation",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="artifactperturbationtarget",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="artifacttechsample",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="artifactwell",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="biologic",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="biosample",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="combinationperturbation",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="compound",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="compoundperturbation",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="donor",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="environmentalperturbation",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="experiment",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="geneticperturbation",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="perturbationtarget",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="techsample",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="well",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
    ]
