# Generated by Django 5.2 on 2025-01-21 14:03

import django.db.models.deletion
import django.db.models.functions.datetime
import lamindb.base.fields
import lamindb.base.ids
import lamindb.base.users
import lamindb.models
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("wetlab", "0026_alter_biosample_artifacts_alter_techsample_artifacts"),
        ("wetlab", "0027_rename_treatment_add_donor"),
        ("wetlab", "0028_remove_combinationperturbation_compounds_and_more"),
        ("wetlab", "0029_artifactbiologic_biologic_artifactbiologic_biologic"),
        ("wetlab", "0030_lamindbv1"),
        ("wetlab", "0031_alter_biologic_space_alter_biosample_space_and_more"),
        ("wetlab", "0032_rename_aux_biologic__aux_rename_aux_biosample__aux_and_more"),
        ("wetlab", "0033_alter_biologic__aux_alter_biosample__aux_and_more"),
        ("wetlab", "0034_lamindbv1_part6"),
    ]

    dependencies = []  # type: ignore

    operations = []  # type: ignore
