# Generated by Django 5.2 on 2025-05-25 11:59

import django.db.models.deletion
import lamindb.base.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0100_branch_alter_artifact__branch_code_and_more"),
        ("wetlab", "0035_alter_biologic_targets_alter_compound_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artifactbiologic",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactbiosample",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactcombinationperturbation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactcompound",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactcompoundperturbation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactdonor",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactenvironmentalperturbation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactexperiment",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactgeneticperturbation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactperturbationtarget",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifacttechsample",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactwell",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterField(
            model_name="biologic",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="biosample",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="combinationperturbation",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="compound",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="compoundperturbation",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="environmentalperturbation",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="geneticperturbation",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="perturbationtarget",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="techsample",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="well",
            name="_branch_code",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="_branch_code",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.branch",
            ),
        ),
    ]
