# Generated by Django 5.2 on 2025-05-25 11:59

import lamindb.base.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wetlab", "0035_alter_biologic_targets_alter_compound_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artifactbiologic",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactbiosample",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactcombinationperturbation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactcompound",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactcompoundperturbation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactdonor",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactenvironmentalperturbation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactexperiment",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactgeneticperturbation",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactperturbationtarget",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifacttechsample",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="artifactwell",
            options={"base_manager_name": "objects"},
        ),
    ]
