# Generated by Django 5.2 on 2025-05-25 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wetlab", "0036_alter_artifactbiologic_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="biologic",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="biosample",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="combinationperturbation",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="compound",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="compoundperturbation",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="donor",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="environmentalperturbation",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="experiment",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="geneticperturbation",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="perturbationtarget",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="techsample",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="well",
            old_name="_branch_code",
            new_name="branch",
        ),
    ]
