# Generated by Django 5.1.12 on 2025-10-01 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wetlab", "0044_alter_biologic_is_locked_alter_biosample_is_locked_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biologic",
            name="page",
        ),
        migrations.RemoveField(
            model_name="biosample",
            name="page",
        ),
        migrations.RemoveField(
            model_name="combinationperturbation",
            name="page",
        ),
        migrations.RemoveField(
            model_name="compound",
            name="page",
        ),
        migrations.RemoveField(
            model_name="compoundperturbation",
            name="page",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="page",
        ),
        migrations.RemoveField(
            model_name="environmentalperturbation",
            name="page",
        ),
        migrations.RemoveField(
            model_name="experiment",
            name="page",
        ),
        migrations.RemoveField(
            model_name="geneticperturbation",
            name="page",
        ),
        migrations.RemoveField(
            model_name="perturbationtarget",
            name="page",
        ),
        migrations.RemoveField(
            model_name="techsample",
            name="page",
        ),
        migrations.RemoveField(
            model_name="well",
            name="page",
        ),
    ]
