# Generated by Django 5.2 on 2026-01-05 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wetlab", "0048_alter_biologic_branch_alter_biosample_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artifactbiologic",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactbiologic",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactbiosample",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactbiosample",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactcombinationperturbation",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactcombinationperturbation",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactcompound",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactcompound",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactcompoundperturbation",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactcompoundperturbation",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactdonor",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactdonor",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactenvironmentalperturbation",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactenvironmentalperturbation",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactexperiment",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactexperiment",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactgeneticperturbation",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactgeneticperturbation",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactperturbationtarget",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactperturbationtarget",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifacttechsample",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifacttechsample",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactwell",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactwell",
            name="label_ref_is_name",
        ),
    ]
